#############################################################################
# Makefile for building: GeneralMDI
# Generated by qmake (2.01a) (Qt 4.7.3) on: gio giu 16 22:12:06 2011
# Project:  GeneralMDI.pro
# Template: subdirs
# Command: /usr/bin/qmake -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger -o Makefile GeneralMDI.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-SchedInt \
		sub-QRollout

SchedInt/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) SchedInt/ || $(MKDIR) SchedInt/ 
	cd SchedInt/ && $(QMAKE) /home/michele2/Dropbox/Progetti/GeneralMDI/SchedInt/SchedInt.pro -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger -o $(MAKEFILE)
sub-SchedInt-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) SchedInt/ || $(MKDIR) SchedInt/ 
	cd SchedInt/ && $(QMAKE) /home/michele2/Dropbox/Progetti/GeneralMDI/SchedInt/SchedInt.pro -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger -o $(MAKEFILE)
sub-SchedInt: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE)
sub-SchedInt-make_default-ordered: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) 
sub-SchedInt-make_default: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) 
sub-SchedInt-make_first-ordered: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) first
sub-SchedInt-make_first: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) first
sub-SchedInt-all-ordered: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) all
sub-SchedInt-all: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) all
sub-SchedInt-clean-ordered: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) clean
sub-SchedInt-clean: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) clean
sub-SchedInt-distclean-ordered: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) distclean
sub-SchedInt-distclean: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) distclean
sub-SchedInt-install_subtargets-ordered: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) install
sub-SchedInt-install_subtargets: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) install
sub-SchedInt-uninstall_subtargets-ordered: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-SchedInt-uninstall_subtargets: SchedInt/$(MAKEFILE) FORCE
	cd SchedInt/ && $(MAKE) -f $(MAKEFILE) uninstall
QRollout/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) QRollout/ || $(MKDIR) QRollout/ 
	cd QRollout/ && $(QMAKE) /home/michele2/Dropbox/Progetti/GeneralMDI/QRollout/QRollout.pro -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger -o $(MAKEFILE)
sub-QRollout-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) QRollout/ || $(MKDIR) QRollout/ 
	cd QRollout/ && $(QMAKE) /home/michele2/Dropbox/Progetti/GeneralMDI/QRollout/QRollout.pro -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger -o $(MAKEFILE)
sub-QRollout: QRollout/$(MAKEFILE) FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE)
sub-QRollout-make_default-ordered: QRollout/$(MAKEFILE) sub-SchedInt-make_default-ordered  FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) 
sub-QRollout-make_default: QRollout/$(MAKEFILE) FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) 
sub-QRollout-make_first-ordered: QRollout/$(MAKEFILE) sub-SchedInt-make_first-ordered  FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) first
sub-QRollout-make_first: QRollout/$(MAKEFILE) FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) first
sub-QRollout-all-ordered: QRollout/$(MAKEFILE) sub-SchedInt-all-ordered  FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) all
sub-QRollout-all: QRollout/$(MAKEFILE) FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) all
sub-QRollout-clean-ordered: QRollout/$(MAKEFILE) sub-SchedInt-clean-ordered  FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) clean
sub-QRollout-clean: QRollout/$(MAKEFILE) FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) clean
sub-QRollout-distclean-ordered: QRollout/$(MAKEFILE) sub-SchedInt-distclean-ordered  FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) distclean
sub-QRollout-distclean: QRollout/$(MAKEFILE) FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) distclean
sub-QRollout-install_subtargets-ordered: QRollout/$(MAKEFILE) sub-SchedInt-install_subtargets-ordered  FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) install
sub-QRollout-install_subtargets: QRollout/$(MAKEFILE) FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) install
sub-QRollout-uninstall_subtargets-ordered: QRollout/$(MAKEFILE) sub-SchedInt-uninstall_subtargets-ordered  FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-QRollout-uninstall_subtargets: QRollout/$(MAKEFILE) FORCE
	cd QRollout/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: GeneralMDI.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/debug.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger -o Makefile GeneralMDI.pro
/usr/lib/qt4/mkspecs/common/g++.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/modules/qt_phonon.pri:
/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/debug.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/lib/qtcreator/share/qtcreator/qml/qmljsdebugger -o Makefile GeneralMDI.pro

qmake_all: sub-SchedInt-qmake_all sub-QRollout-qmake_all FORCE

make_default: sub-SchedInt-make_default-ordered sub-QRollout-make_default-ordered FORCE
make_first: sub-SchedInt-make_first-ordered sub-QRollout-make_first-ordered FORCE
all: sub-SchedInt-all-ordered sub-QRollout-all-ordered FORCE
clean: sub-SchedInt-clean-ordered sub-QRollout-clean-ordered FORCE
distclean: sub-SchedInt-distclean-ordered sub-QRollout-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-SchedInt-install_subtargets-ordered sub-QRollout-install_subtargets-ordered FORCE
uninstall_subtargets: sub-SchedInt-uninstall_subtargets-ordered sub-QRollout-uninstall_subtargets-ordered FORCE

sub-SchedInt-check_ordered: SchedInt/$(MAKEFILE)
	cd SchedInt/ && $(MAKE) check
sub-QRollout-check_ordered: QRollout/$(MAKEFILE) sub-SchedInt-check_ordered 
	cd QRollout/ && $(MAKE) check
check: sub-SchedInt-check_ordered sub-QRollout-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

